server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/accountdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true